// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytgmgoiyqbiqvgqyfahb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Z21nb2l5cWJpcXZncXlmYWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzUwMjcsImV4cCI6MjA2Mzg1MTAyN30.tIC-2ycYgvDbMQh5WnSP_FcWv4lViObN_zfpp5KFzaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);