// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ochtjjvkenxucmamjsca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaHRqanZrZW54dWNtYW1qc2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODg1MzksImV4cCI6MjA2Mjc2NDUzOX0.HHTTCEYsfO3cd9Pjwyxa9XaWnDNTjHBZGxpTBha2ImI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);